version: "3.8"
 
services:
  backend:
    build: ./backend  # Path to the backend Dockerfile
    ports:
      - "8000:8000"  # Exposes backend port
    volumes:
      - ./backend:/app  # Mounts the code for development (optional)
    environment:
      - ENVIRONMENT=production  # Sets the environment variable
    networks:
      - mynetwork  # Network for inter-container communication
    restart: always  # Ensures the container restarts automatically after reboot

  frontend:
    build: ./frontend  # Path to the frontend Dockerfile (Nginx)
    ports:
      - "3000:3000"  # Exposes frontend port
    depends_on:
      - backend  # Ensures backend starts before frontend
    networks:
      - mynetwork  # Network for inter-container communication
    restart: always  # Ensures the container restarts automatically after reboot

networks:
  mynetwork:
    driver: bridge  # Defines the network type for containers
