version: "3.8"
 
services:
  backend:
    build: ./backend  # Path to the backend Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Mounts the code for development (optional)
    environment:
      - ENVIRONMENT=production
    networks:
      - mynetwork

  frontend:
    build: ./frontend  # Path to the frontend Dockerfile (Nginx)
    ports:
      - "80:80"  # Serves on port 80
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge